// Font Awesome icon exports for easy reuse
import {
  faDollarSign,
  faChartLine,
  faWallet,
  faStickyNote,
  faChartBar,
  faBriefcase,
  faCoins,
  faGem,
  faArrowTrendUp,
  faArrowTrendDown,
  faFileInvoiceDollar,
  faCreditCard,
  faNoteSticky,
  faChartLine as faStockChart,
  faSackDollar,
  faCircleDollarToSlot,
  faCalendar,
  faTag,
  faTrash,
  faEdit,
  faPlus,
  faMinus,
  faRefresh,
  faArrowLeft,
  faBuildingColumns,
  faMoneyBillWave,
  faPiggyBank,
  faLandmark,
  faChartPie,
  faHandHoldingDollar
} from '@fortawesome/free-solid-svg-icons'

export const icons = {
  dollar: faDollarSign,
  chart: faChartLine,
  wallet: faWallet,
  note: faStickyNote,
  chartBar: faChartBar,
  briefcase: faBriefcase,
  coins: faCoins,
  gem: faGem,
  bitcoin: faCoins,
  ethereum: faGem,
  arrowUp: faArrowTrendUp,
  arrowDown: faArrowTrendDown,
  invoice: faFileInvoiceDollar,
  creditCard: faCreditCard,
  stickyNote: faNoteSticky,
  stockChart: faStockChart,
  sackDollar: faSackDollar,
  circleDollar: faCircleDollarToSlot,
  calendar: faCalendar,
  tag: faTag,
  trash: faTrash,
  edit: faEdit,
  plus: faPlus,
  minus: faMinus,
  refresh: faRefresh,
  arrowLeft: faArrowLeft,
  bank: faBuildingColumns,
  money: faMoneyBillWave,
  savings: faPiggyBank,
  landmark: faLandmark,
  chartPie: faChartPie,
  handDollar: faHandHoldingDollar
}

